### ISSUE TITLE
vellvm as a library

### ISSUE THREAD

**Issue by zoep** [vellvm/vellvm#385]
Hello,

We’re interested in using Vellvm as a library, so that we can target LLVM IR from a compiler we're developing within Rocq. We're less concerned with using the executable interpreter and more focused on generating and manipulating LLVM IR.

What’s the recommended way to integrate Vellvm in this manner? If we install the OPAM package, will it expose the necessary library for use within Rocq?

Thanks in advance for your help!

**Comment by Chobbes** [comment]
Hello @zoep. Yes, if you install Vellvm from OPAM it will install Vellvm for use as a library as well (at least it should! I use nix so I can't confirm, but this *should* be the case). The proofs take a fair bit of time to compile, but beyond that it should be a simple opam install.

Please let us know if there are any problems!

**Comment by zoep** [comment]
Great, thanks so much! Will keep you posted if I have any issues.

**Comment by Chobbes** [comment]
Oh, one other thing is that the latest version should be `rocq-vellvm` on opam, assuming you're on 9.0. I'm a little fuzzy on what happens with the existing `coq-vellvm` on opam and how it selects between the two.

**Comment by Zdancewic** [comment]
One more thing:  we don't have a whole lot of support yet for programmatically generating LLVM IR within Rocq - you'll need to manipulate control-flow graphs, generate names, etc.   But we have thought a bit about good structures for doing that, and some of our experimental branches have features that might make this easier (e.g. by changing the representation of graphs to be maps instead of lists).  I think our group would be very interested in helping develop some general-purpose library support for doing code generation that targets Vellvm -- so do let us know what you need / are up to; we're happy to help out!

**Comment by zoep** [comment]
Hi Steve, thanks for your message! We would like like to use vellvm in order to taraget LLVM IR from CertiCoq. Essentially, we want to compile a purely functional ANF IR to LLVM IR. Do you think this is doable with vellvm?

**Comment by Zdancewic** [comment]
It should be doable -- assuming you've already done closure conversion and hoisting.  I assume that this would be the last step in your $\lambda_{ANF}$ backend?  That shouldn't be too bad, assuming you have a translation to LLVM IR's types for things like constructors and closures.  Targeting Vellvm's LLVMAst shouldn't be too bad.

If you want to also do a proof of correctness I expect that reconciling the operational semantics and memory model of $\lambda_{ANF}$ with Vellvm's itrees based semantics might be the interesting / hard part.  We did something like that for the HELIX compiler.  Basically we (1) relate an existing operational semantics to an itree-based denotational semantics and then (2) prove the compiler correct by relational reasoning on the denotations.  There we had the luxury of using the same memory model on both sides; I'm not sure whether that would be the case for your situation.

**Comment by zoep** [comment]
OK, good to know! Yes, λANF is fully closure converted and hoisted at this last stage. 

Thanks for the proof tips! Our first goal is a working compiler pass, but we might try to prove it correct later on. And yes, we will have to deal the change of the memory model (similar to our λANF - Clight pass).

**Comment by zoep** [comment]
Hi again! 

I am trying to install vellvm for Coq 8.20.1 using opam (since we haven't updated CertiCoq to Rocq yet). However, I am getting spurious compilation errors. Is this expected? Is there anyway to overcome this and install vellvm as an opam package for Coq 8.20? 

For reference, I am trying to run `opam install coq-vellvm.v2.0.20250110` with Coq 8.20.1 compiled with OCaml 4.14.2.

**Comment by Chobbes** [comment]
@zoep we definitely have not maintained backwards compatibility when updating to Rocq 9.0. The version that you're installing appears to be this one, though https://github.com/vellvm/vellvm/releases/tag/v2.0.20250110, and that should work with 8.20.1. If you are getting compilation errors it is likely due to the versions of some libraries. Can you post the errors that you are getting?

**Comment by Chobbes** [comment]
@zoep in case this is helpful, here are all of the libraries that I had for this release and their versions.

> mathcomp-all-2.2.0
> mathcomp-ssreflect-2.2.0
> hierarchy-builder-1.7.0
> elpi-2.2.0
> mathcomp-fingroup-2.2.0
> mathcomp-algebra-2.2.0
> mathcomp-solvable-2.2.0
> mathcomp-field-2.2.0
> mathcomp-character-2.2.0
> coq-ext-lib-0.12.1
> paco-4.2.0
> InteractionTrees-5.2.0
> flocq-4.2.0
> ceres-0.4.1
> simple-io-1.10.0
> QuickChick-2.0.4

I did build it with 8.20.0, but I'll double check with 8.20.1. Typically in the past version bumps to ext-lib, InteractionTrees, and flocq have cause problems.

**Comment by Chobbes** [comment]
Ah, I think paco 4.2.3 might be the problem. They added some hints to the proof database so automation solves more things. I have fixes for this in this branch that you might want to try:

https://github.com/vellvm/vellvm/tree/v2.0.20250110-paco-4.2.3

I have this building with these versions:

> mathcomp-all-2.4.0
> mathcomp-character-2.4.0
> mathcomp-field-2.4.0
> mathcomp-solvable-2.4.0
> mathcomp-algebra-2.4.0
> mathcomp-boot-2.4.0
> hierarchy-builder-1.9.1
> elpi-2.6.0
> mathcomp-fingroup-2.4.0
> coq-ext-lib-0.13.0
> paco-4.2.3
> InteractionTrees-5.2.1
> flocq-4.2.1
> ceres-0.4.1
> simple-io-1.10.0
> QuickChick-2.0.4

**Comment by zoep** [comment]
We managed to make it work with 8.20! Thank you so much for your help!
